export default [
    "A-Bomb",
    "Abe Sapien",
    "Abin Sur",
    "Abomination",
    "Abraxas",
    "Absorbing Man",
    "Adam Monroe",
    "Adam Strange",
    "Agent Bob",
    "Agent Zero",
    "Air-Walker",
    "Ajax",
    "Alan Scott",
    "Alex Mercer",
    "Alfred Pennyworth",
    "Alien",
    "Amazo",
    "Angel",
    "Angel",
    "Angel Dust",
    "Angel Salvadore",
    "Animal Man",
    "Annihilus",
    "Ant-Man",
    "Ant-Man II",
    "Anti-Monitor",
    "Anti-Venom",
    "Apocalypse",
    "Aquababy",
    "Aqualad",
    "Aquaman",
    "Arachne",
    "Archangel",
    "Arclight",
    "Ardina",
    "Ares",
    "Ariel",
    "Armor",
    "Atlas",
    "Atlas",
    "Atom Girl",
    "Atom II",
    "Aurora",
    "Azazel",
    "Azrael",
    "Bane",
    "Banshee",
    "Bantam",
    "Batgirl",
    "Batgirl IV",
    "Batgirl VI",
    "Batman",
    "Batman",
    "Batman II",
    "Battlestar",
    "Batwoman V",
    "Beast",
    "Beast Boy",
    "Ben 10",
    "Beta Ray Bill",
    "Beyonder",
    "Big Barda",
    "Big Daddy",
    "Big Man",
    "Bill Harken",
    "Bionic Woman",
    "Bird-Brain",
    "Bishop",
    "Bizarro",
    "Black Adam",
    "Black Bolt",
    "Black Canary",
    "Black Canary",
    "Black Cat",
    "Black Flash",
    "Black Knight III",
    "Black Lightning",
    "Black Mamba",
    "Black Manta",
    "Black Panther",
    "Black Widow",
    "Blackout",
    "Blackwing",
    "Blackwulf",
    "Blade",
    "Bling!",
    "Blink",
    "Blizzard II",
    "Blob",
    "Bloodaxe",
    "Bloodhawk",
    "Blue Beetle III",
    "Boba Fett",
    "Boom-Boom",
    "Box IV",
    "Brainiac",
    "Brainiac 5",
    "Brundlefly",
    "Buffy",
    "Bullseye",
    "Shaktiman"
]